# Generated by Django 5.2 on 2026-02-08 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("todo", "To do"), ("in_progress", "In progress"), ("done", "Done")],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("priority", models.IntegerField(choices=[(1, "Low"), (2, "Medium"), (3, "High")], default=2)),
                ("deadline", models.DateField(blank=True, help_text="Optional deadline for the task", null=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="task_scheduler.project"
                    ),
                ),
            ],
        ),
    ]
