# Generated by Django 5.2 on 2026-02-11 23:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="project_id",
            new_name="project",
        ),
    ]
